### ISSUE TITLE
데이터 파일 생성

### ISSUE THREAD

**Issue by STR-HK** [SHI3DO/Paffy#4]
파일매니저에서 파일을 전부 생성하면,
추후 기능 추가가 불편해집니다.

이를 방지하기 위해서 이 기능을 함수로 대체하여
기능 추가 파일에서의 데이터 파일을 생성하는 방식 건의드립니다.

잘 고려해주시면 감사하겠습니다.

**Comment by SHI3DO** [comment]
네

**Comment by SHI3DO** [comment]
python -> js
